-- MySQL Script generated by MySQL Workbench
-- Sun Apr 21 14:22:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pooa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pooa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pooa` DEFAULT CHARACTER SET utf8 ;
USE `pooa` ;

-- -----------------------------------------------------
-- Table `pooa`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`Sala` (
  `idSala` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  `Capacidade` INT NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooa`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `Cargo` VARCHAR(255) NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooa`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`Equipamento` (
  `idEquipamento` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooa`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `Sala` INT NOT NULL,
  `Data` DATETIME NOT NULL,
  `Pauta` LONGTEXT NULL,
  `Ata` LONGTEXT NULL,
  `Funcionario` INT NOT NULL,
  `DataFim` DATETIME NOT NULL,
  INDEX `fk_Reserva_Sala_idx` (`Sala` ASC) VISIBLE,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Funcionario1_idx` (`Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Sala`
    FOREIGN KEY (`Sala`)
    REFERENCES `pooa`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Funcionario1`
    FOREIGN KEY (`Funcionario`)
    REFERENCES `pooa`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooa`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`Participante` (
  `Reserva` INT NOT NULL,
  `Funcionario` INT NOT NULL,
  `AceitouAta` TINYINT NULL,
  INDEX `fk_Reserva_has_Funcionario_Funcionario1_idx` (`Funcionario` ASC) VISIBLE,
  INDEX `fk_Reserva_has_Funcionario_Reserva1_idx` (`Reserva` ASC) VISIBLE,
  PRIMARY KEY (`Reserva`, `Funcionario`),
  CONSTRAINT `fk_Reserva_has_Funcionario_Reserva1`
    FOREIGN KEY (`Reserva`)
    REFERENCES `pooa`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Funcionario_Funcionario1`
    FOREIGN KEY (`Funcionario`)
    REFERENCES `pooa`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pooa`.`ReservaEquipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pooa`.`ReservaEquipamento` (
  `idReservaEquipamento` INT NOT NULL AUTO_INCREMENT,
  `Equipamento` INT NOT NULL,
  `Reserva` INT NOT NULL,
  PRIMARY KEY (`idReservaEquipamento`),
  INDEX `fk_ReservaEquipamento_Equipamento1_idx` (`Equipamento` ASC) VISIBLE,
  INDEX `fk_ReservaEquipamento_Reserva1_idx` (`Reserva` ASC) VISIBLE,
  CONSTRAINT `fk_ReservaEquipamento_Equipamento1`
    FOREIGN KEY (`Equipamento`)
    REFERENCES `pooa`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservaEquipamento_Reserva1`
    FOREIGN KEY (`Reserva`)
    REFERENCES `pooa`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
